import "./globals.css";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import Navbar from "../components/navbar";
// import favion from "../../public/logo.ico";
import NextAuthSessionProvider from "./Providers/nextSessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  display: "swap"
});

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={nunito_sans.className}>
      <body>
        <NextAuthSessionProvider>
          {/* <Navbar /> */}
          {children}

        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
